[package]
name = "pythia"
version = "3.2.0"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
repository = "https://github.com/m1sk9/Pythia"
readme = "README.md"
description = "A Discord bot that bridges your server and LLM APIs."

[dependencies]
anyhow = "1.0"
base64 = "0.23"
bytes = "1"
dotenvy = "0.15"
envy = "0.4"
jiff = { version = "0.2", features = ["tzdb-bundle-always"] }
reqwest = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
toml = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
twilight-cache-inmemory = "0.17"
twilight-gateway = "0.17"
twilight-http = "0.17"
twilight-model = "0.17"
twilight-util = { version = "0.17", features = ["builder"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
